services:
  postgis_db:
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_DB: o2p
      POSTGRES_USER: o2p
      POSTGRES_PASSWORD: o2p
    ports:
      - 5432:5432
    volumes:
      - ./data/postgis:/var/lib/postgresql/data
      - ./database/init.sql:/database/scripts/init.sql
    deploy:
      resources:
        limits:
          cpus: "4" # Allocate 2 CPUs
          memory: 4G # Allocate 8GB of memory

  osm2pgrouting:
    depends_on:
      - postgis_db
    build:
      context: .
    environment:
      PGPASSWORD: o2p
    deploy:
      resources:
        limits:
          cpus: "4" # Allocate 2 CPUs
          memory: 8G # Allocate 8GB of memory
